```{r, message=F, echo=F}
library(tidyverse)
library(patchwork)
## setwd("/Users/beelee/Desktop/Columbia/Fall_2021/P8130-Biostatistical_Methods_1/Project/p8130_final_project/")
```


```{r, message=F, echo=F}
cdi_df = 
  read_csv("./data/cdi.csv") %>% 
  mutate(
    CRM_1000 = crimes/pop * 1000,
    dens = pop/area,
    region = factor(region, labels =c("Northeast", "North Central", "South", "West")),
    state = factor(state),
    docbed = docs/beds,
    log_pop18 = log(pop18),
    log_pop65 = log(pop65),
    log_hsgrad = log(hsgrad),
    log_bagrad = log(bagrad),
    log_poverty = log(poverty),
    log_unemp = log(unemp),
    log_pcincome = log(pcincome),
    log_totalinc = log(totalinc),
    log_docbed = log(docbed),
    log_dens = log(dens)
  ) %>% 
  dplyr::select(-id, -cty, -docs, -beds, -crimes, -pop, -area) %>% 
  dplyr::select(CRM_1000, state, region, everything())

cdi_df_long = 
  cdi_df %>% 
    pivot_longer(
      pop18:log_dens,
      names_to = "var",
      values_to = "val"
    ) %>% 
  mutate(
    trans = case_when(grepl('log_', var) ~ 'log',
                     TRUE ~ 'ori'
    ),
    trans = factor(trans, levels = c("ori", "log"), labels =c("Untransformed", "log Transformed")),
    var = str_replace(var, "log_", ""),
    var = factor(var, levels = c("pop18", "pop65", "hsgrad", "bagrad", "poverty", "unemp", "pcincome", "totalinc", "dens", "docbed"))
  )

dens_plot_gen = function(v, b){
  
  if(!b){
    cdi_df_long %>% 
      filter(var == v) %>% 
      ggplot(aes(x = val)) +
      geom_boxplot() +
      theme_minimal() +
      theme(
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x=element_blank()
      ) +
      facet_grid(var ~ trans, switch = "y", scales = "free") +
      theme(
        strip.text.y.left = element_text(angle = 0),
        strip.text.x = element_blank()
      )
  }else{
    cdi_df_long %>% 
      filter(var == v) %>% 
      ggplot(aes(x = val)) +
      geom_boxplot() +
      theme_minimal() +
      theme(
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        axis.text.y=element_blank(),
        axis.text.x=element_blank()
      ) +
      facet_grid(var ~ trans, switch = "y", scales = "free") +
      theme(
        strip.text.y.left = element_text(angle = 0)
      )
  }
}

var_list = c("pop18", "pop65", "hsgrad", "bagrad", "poverty", "unemp", "pcincome", "totalinc", "dens", "docbed")

plot_1 = dens_plot_gen(var_list[1], T)
plot_2 = dens_plot_gen(var_list[2], F)
plot_3 = dens_plot_gen(var_list[3], F)
plot_4 = dens_plot_gen(var_list[4], F)
plot_5 = dens_plot_gen(var_list[5], F)
plot_6 = dens_plot_gen(var_list[6], F)
plot_7 = dens_plot_gen(var_list[7], F)
plot_8 = dens_plot_gen(var_list[8], F)
plot_9 = dens_plot_gen(var_list[9], F)

patch_1 = plot_1 / plot_2 / plot_3 / plot_4 / plot_5 / plot_6 / plot_7 / plot_8 / plot_9

patch_1 + 
  plot_annotation(title = 'Untransformed and log Transformed Variable Distributions in the CDI Dataset',
                  theme = theme(plot.title = element_text(size = 14)))
```


```{r, message=F, echo=F}
plot_10 = 
  cdi_df %>%
  group_by(state) %>% 
  summarise(n = n()) %>%
  ggplot() + 
  geom_col(aes(state, n)) +
  theme(
    axis.text.x = element_text(angle = 90),
    axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank()
  )

plot_11 =
  cdi_df %>%
  group_by(region) %>% 
  summarise(n = n()) %>%
  ggplot() + 
  geom_col(aes(region, n)) +
  theme(
    axis.title.y=element_blank(),
    axis.text.y=element_blank(),
    axis.ticks.y=element_blank(),
    axis.ticks.x=element_blank()
  )

patch_2 = plot_10 / plot_11

patch_2 + 
  plot_annotation(title = 'Location Frequency Distribution in the CDI Dataset',
                  theme = theme(plot.title = element_text(size = 14)))

```

